CREATE DATABASE COMPANY_1;
USE COMPANY_1;
CREATE TABLE DEPARTMENTS(DEPT_ID INT, DEPT_NAME VARCHAR(30));
CREATE TABLE STAFF(STAFF_ID INT, FULL_NAME VARCHAR(30),EMAIL VARCHAR(50));
SHOW TABLES;
ALTER TABLE STAFF
MODIFY COLUMN STAFF_ID INT PRIMARY KEY AUTO_INCREMENT;
SHOW CREATE TABLE STAFF;
ALTER TABLE DEPARTMENTS
MODIFY COLUMN DEPT_ID INT PRIMARY KEY;
SHOW CREATE TABLE DEPARTMENTS;
ALTER TABLE STAFF
MODIFY COLUMN  FULL_NAME VARCHAR(30)  NOT NULL;

ALTER TABLE STAFF
MODIFY COLUMN  EMAIL VARCHAR(50) UNIQUE;

ALTER TABLE DEPARTMENTS
MODIFY COLUMN DEPT_NAME VARCHAR(30) NOT NULL;

ALTER TABLE STAFF
ADD COLUMN AGE INT;
SHOW CREATE TABLE STAFF;

ALTER TABLE STAFF
MODIFY AGE INT CHECK(AGE>18);

ALTER TABLE STAFF
ADD COLUMN CITY VARCHAR(30) DEFAULT "HYDERABAD";
SHOW CREATE TABLE STAFF;

ALTER TABLE STAFF
ADD COLUMN DEPT_ID INT;

SHOW CREATE TABLE STAFF;
SHOW CREATE TABLE DEPARTMENTS;

ALTER TABLE STAFF
ADD FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS (DEPT_ID);

SHOW CREATE TABLE STAFF;
SHOW CREATE TABLE DEPARTMENTS;


-- DROP FOREIGN KEY

ALTER TABLE STAFF
DROP FOREIGN KEY staff_ibfk_1;
SHOW CREATE TABLE STAFF;

-- DROP PRIMARY KEY

ALTER TABLE DEPARTMENTS
DROP PRIMARY KEY;
SHOW CREATE TABLE DEPARTMENTS;


-- DROP UNIQUE ON EMAIL

ALTER TABLE STAFF
DROP INDEX EMAIL;
SHOW CREATE TABLE STAFF;

-- REMOVE CHECK ON AGE 

ALTER TABLE STAFF
DROP CHECK staff_chk_1;
SHOW CREATE TABLE STAFF;

-- DROP NOT NULL ON DEPT_ID , DEPT_NAME
ALTER TABLE DEPARTMENTS
MODIFY DEPT_ID INT NULL;
ALTER TABLE DEPARTMENTS
MODIFY DEPT_NAME VARCHAR(30) NULL;
SHOW CREATE TABLE DEPARTMENTS;


-- DROPPING NOT NULL AND DEFAULT
ALTER TABLE STAFF
MODIFY FULL_NAME VARCHAR(30) NULL;
SHOW CREATE TABLE STAFF;
ALTER TABLE STAFF
MODIFY CITY VARCHAR(30);
SHOW CREATE TABLE STAFF;


-- DROPPING AUTO INCREMENT AND PRIMARY KEY IN STAFF TABLE

 ALTER TABLE STAFF
 MODIFY STAFF_ID INT;
 ALTER TABLE STAFF
 DROP PRIMARY KEY;
 
 ALTER TABLE STAFF
DROP INDEX DEPT_ID;
SHOW CREATE TABLE STAFF;


















